#!/bin/bash

mkdir logs


chmod +x ~/binder/start.mongodb 
chmod +x ~/binder/start.adminmongo 

# starting mongodb
~/binder/start.mongodb   &

# starting adminmongo in parallel
# ~/binder/start.adminmongo   &

# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"
